version: "3.9"
services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
        ports:
            - "10000-10002:10000-10002"
    server:
        image:
            shuttle/contentstore/server
        volumes:
            - type: bind
              source: ./Shuttle.ContentStore.Server.config
              target: /opt/shuttle.contentstore.server/Shuttle.ContentStore.Server.dll.config
        depends_on:
            - "azurite"
        build:
            context: .
            dockerfile: dockerfile-server
    web-api:
        image:
            shuttle/contentstore/webapi
        ports:
            - "7599:7599"
        volumes:
            - type: bind
              source: ./Shuttle.ContentStore.WebApi.config
              target: /opt/shuttle.contentstore.webapi/Shuttle.ContentStore.WebApi.dll.config
        environment:
            - ASPNETCORE_URLS=http://*:7599
        depends_on:
            - "azurite"
            - "server"
        build:
            context: .
            dockerfile: dockerfile-webapi   