FROM mcr.microsoft.com/dotnet/runtime:5.0

COPY ./deployment/Shuttle.ContentStore.Server/. /opt/shuttle.contentstore.server/.

ENTRYPOINT ["/opt/shuttle.contentstore.server/Shuttle.ContentStore.Server"]